### ISSUE TITLE
what is this repository?

### ISSUE THREAD

**Issue by SalimiHabib** [hyperledger/aries-mobileagent-xamarin#11]
hi 
**AMA-X extends Aries Framework for .NET , in the context of a mobile app to realize a mobile agent.** , it's mean that we should use this project as guideline for our xamarin project or there is a nugget to use , such as  Aries .
also Aries is agent on its own , and Indy have agent similar to Aries , 

Please specify which one should I use for xamarin , why so many agent , I'm sure there is conflict in naming

**Comment by horationunez** [comment]
The Aries-MobileAgent-Xamarin is a **Xamarin** cross platform solution that uses the **Aries Framework .NET** to provide a basic implementation of a **Mobile Wallet**.

A *Mobile Wallet* is an App that runs on a mobile device that, through a (hopefully friendly) UI, enables an end user to control an Indy wallet that is local to the device.

Because this App connects with other Hyperledger-based services using the Agent protocol we refer to this App as a **Mobile Agent.**

If you want to start a Mobile Agent using the .NET this is a great starting point.
