### ISSUE TITLE
Network subsystem is down

### ISSUE THREAD

**Issue by lijiachuan1982** [hyperledger/aries-mobileagent-xamarin#12]
Hi team, I tried to run this in the anroid simulator on Windows 10 OS, I followed the instruction that after clone the code, run the mediator with `dotnet run` without any error, and also download the libs and place them into the libs folder, and at last I run the mobile app in the andraoid simulator and tried to create a wallet, but it returned "Failed to create wallet: Network subsystem is down", there is no any log generated in the mediator command window. Seems the mobile simulator could not connect to the mediator. One more information about this issue is, when I tried to run the android app from Visual Studio, I selected "Osma.Mobile.App.Android" then selected my created Android simulator.Any suggestion on this issue? Thanks.

**Comment by pstuermlinger** [comment]
I have the exact same problem, even though I got 1 step ahead.

The Mediator is listening to `localhost:5000`. Output:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\myuser\source\repos\aries-mobileagent-xamarin\mediator
```

The Android emulator could not connect to the hosts localhost via Chrome. However, it worked with `10.0.2.2:5000`. So I set the endpoint uri to `10.0.2.2:5000` in Osma.Mobile.App->App.xaml->App.xaml.cs line 65.

Now, when I click on `Create Wallet` in the OSMA app, the mediator log prints...
```
info: Hyperledger.Aries.Features.DidExchange.DefaultConnectionService[4010]
      ConnectionId a16f1686-bdc9-4055-8e1e-72959814db0b
```
...while OSMA still shows the throbber. After a few seconds it errors with a `Failed to create wallet: Network subsystem is down` again - without any further logs in the mediator.
So connecting the mediator seems to be working, but something else fails.

Any ideas?

**Comment by pstuermlinger** [comment]
Got it working with a ngrok endpoint. Make sure to delete `%USERPROFILE%/.indy_wallet/wallet` after changing the mediator's endpoint uri.

**Comment by doganomer** [comment]
I had the same issue. AVD cannot reach to _http://localhost:5000_ address (as expected?).  Using 10.0.2.2 instead of localhost can access to _http://10.0.2.2:5000/.well-known/agent-configuration_. However, the mediator agent configuration returns localhost as the ServiceEndpoint; although EndPointUri option is configured with 10.0.2.2 as follows in the mediator: 

options.EndpointUri = "http://10.0.2.2:5000";

Here is the response that the mobile agent gets from _http://10.0.2.2:5000/.well-known/agent-configuration_

{"ServiceEndpoint":"http://localhost:5000","RoutingKey":"6JqWGVshN83z2iekNitpz5CVkPhqBTtYgyN5V59ChnAm","Invitation":{"label":null,"imageUrl":null,"serviceEndpoint":"http://localhost:5000","routingKeys":null,"recipientKeys":["4b8cii9VfYc15yRmAekocgPqUm3sEqJvNCFT714YSBgJ"],"@id":"b51f3a9d-c077-4e9c-a338-c4307bb2b2a3","@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation"}}

Therefore, mobile agent cannot continue the wallet creation process.
