### ISSUE TITLE
Android - The requested pool cannot be opened because it does not have an existing configuration

### ISSUE THREAD

**Issue by sahil-khanna** [hyperledger/aries-mobileagent-xamarin#19]
**Problem Statement**
When accepting a Credential offer, the error `The requested pool cannot be opened because it does not have an existing configuration` is thrown on executing the below code

`(CredentialRequestMessage credentialRequestMessage, CredentialRecord newCredentialRecord) = await credentialService.CreateRequestAsync(agentContext, Credential.Record.Id);`

On investigating, I found that the [PoolConfigurator](https://github.com/hyperledger/aries-mobileagent-xamarin/blob/2f222a3b72169cfac94f494c54f306172f7ecf99/src/Osma.Mobile.App/Services/PoolConfigurator.cs#L53) gets an exception (**An IO error occurred**). Below is the stack trace

`at Hyperledger.Aries.Ledger.DefaultPoolService.CreatePoolAsync (System.String poolName, System.String genesisFile) [0x0002d] in D:\a\1\s\src\Hyperledger.Aries\Ledger\DefaultPoolService.cs:59 
  at SSI.Services.PoolConfigurator.ConfigurePoolsAsync () [0x0023b] in /Users/sahil.khanna/Documents/VisualStudio_Workspace/ssi-mobile-app/SSI/Services/PoolConfigurator.cs:54`

**Note**

- The above scenario works fine on iOS. The problem is on an Android emulator and a device.
- The `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions are granted

**Comment by horationunez** [comment]
hey @sahil-khanna, the problem you are having is that you are running on an Android runtime version that doesn't really grant permission using those attributes (while confirming wrongly that you have it).

This is a due to a change in Android 10/11 that introduces the notion of scoped storage as a new way to secure this permissions..  there is a way to request a legacy treatment of this permissions.

Take a look at the changes I proposed here: https://github.com/hyperledger/aries-mobileagent-xamarin/pull/21

**Comment by sahil-khanna** [comment]
Thanks, @horationunez. The below worked for me

Add the following attribute in the `<application/>` tag of the AndroidManifest.xml

`android:requestLegacyExternalStorage="true"`
